import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import InvoiceList from '@/components/InvoiceList'
import { useState } from 'react'
import Banner from '@/components/Banner'
var axios =require('axios')


const inter = Inter({ subsets: ['latin'] })
export default function AllInvoices({data}) {
    const [invoices, setInvoices]= useState(data)
  return (
    <>
      <Head>
        <title>CrediTail | Invoices</title>
        <meta name="description" content="Generated by Sashank Deb" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner title={"Invoices"} backBtn={"/"}/>
            <InvoiceList invoices={invoices}/>
      </main>
    </>
  )
}

export async function getServerSideProps() {
    // Fetch data from external API
  let config = {
    method: 'get',
    url:`http://localhost:3000/api/hello`
  };
  
  let res = await axios(config)
    // Pass data to the page via props
    let invoices= await res.data
    return { props: { data: invoices }}
  }
