import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>CrediTail | Home</title>
        <meta name="description" content="Generated by Sashank Deb" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main +" "+ styles.wrapper}>
            <h2 className={inter.className}>
              Welcome to CrediTail
            </h2>
            <Link href="/allinvoice">
            <button className={inter.className}>
              See my invoives <span className={inter.className}>-&gt;</span>
            </button>
            </Link>
      </main>
    </>
  )
}
